作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [3]:
import numpy as np

In [10]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
oarray = np.matmul(array1, array2)
oarray

array([[1., 0.],
       [0., 1.]])

In [11]:
#2. 運用上列array計算特徵值、特徵向量?
x, y = np.linalg.eig(array1)


In [18]:
x,y


(array([13.,  2.]), array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [ ]:
#3. 運用上列array計算SVD?

In [19]:
u , s , vh = np.linalg.svd(array1)


In [20]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [21]:
s

array([13.94721714,  1.86417116])

In [22]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])